# Configuartion Options for guard-autoupload

opts = {
    :protocol => :sftp,       # protocol used to connect to remote host
                              # either sftp or ftp
    :host => "remote_host",
    :user => "username",
    :password => "password",
    :remote => "remote_path",
    :verbose => false,        # if true you get all outputs
    :quiet => false           # if true outputs only on exceptions.
}

guard :autoupload, opts do
    watch(/^((?!Guardfile$).)*$/)
    # Matches every other file but Guardfile. This way we don't
    # accidentally upload the credentials.
end
